# Generated by Django 3.2.4 on 2021-06-07 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category_food.company'),
        ),
    ]
